### ISSUE TITLE
script barfs when it encounters a hole in the data

### ISSUE THREAD

**Issue by riklmr** [riklmr/chaudfontaine#1]
replay:
http://voies-hydrauliques.wallonie.be/opencms/opencms/fr/hydro/Archive/annuaires/stathorairetab.do?code=52840015&annee=2009&mois=1&xt=prt
shows empty cells: gemmenich is missing precipitation data from 17:00 on Jan 6th 2009 until 14:00 the next day.

Script throws:
5284 precipitation 2009 1 http://voies-hydrauliques.wallonie.be/opencms/opencms/fr/hydro/Archive/annuaires/stathorairetab.do?code=52840015&annee=2009&mois=1&xt=prt
Traceback (most recent call last):
  File "get_measurements_wallonie.py", line 448, in <module>
    etl_meuse_alltime(type_test)
  File "get_measurements_wallonie.py", line 424, in etl_meuse_alltime
    etl_station_alltime(station_code, station_type)
  File "get_measurements_wallonie.py", line 436, in etl_station_alltime
    etl_station_month(station_code, station_type, year, month)
  File "get_measurements_wallonie.py", line 400, in etl_station_month
    measurements_df = parseMeasurements(soup)
  File "get_measurements_wallonie.py", line 235, in parseMeasurements
    X[hour - 1, day - 1] = float(measurement.text)
IndexError: index 7 is out of bounds for axis 1 with size 7

**Comment by riklmr** [comment]
Growing the numpy array dynamically depending on the availability of data (does the cell contain text?) is biting us in the neck here.
When the script encounters the empty cell (Jan 7th 2009) in the top row, it does not grow the table. Then it encounters data in the next cell of that row (for Jan 8th) and it is now missing a column in the array to put it in. Hence IndexError.

**Comment by riklmr** [comment]
solved with [7a6dc4457e4f43a985c453b5c68d22b432906f1c](https://github.com/riklmr/chaudfontaine/commit/7a6dc4457e4f43a985c453b5c68d22b432906f1c)

**Comment by riklmr** [comment]
solved with 7a6dc4457e4f43a985c453b5c68d22b432906f1c
