### ISSUE TITLE
Hauteur does not work, at all

### ISSUE THREAD

**Issue by riklmr** [riklmr/chaudfontaine#3]
Just goes to show: retrieving a table by numeric index may be less than robust. Is this really the cause of the following?
```
113 stations(s) retrieved
found 86 stations in db in watershed Meuse
2536 hauteur 2009 1 http://voies-hydrauliques.wallonie.be/opencms/opencms/fr/hydro/Archive/annuaires/stathorairetab.do?code=25361011&annee=2009&mois=1&xt=prt
Traceback (most recent call last):
  File "get_measurements_wallonie.py", line 519, in <module>
    etl_meuse_month(type_test, year_test, month_test)
  File "get_measurements_wallonie.py", line 474, in etl_meuse_month
    etl_station_month(station_code, station_type, year, month)
  File "get_measurements_wallonie.py", line 462, in etl_station_month
    measurements_dict = parseMeasurements(soup)
  File "get_measurements_wallonie.py", line 271, in parseMeasurements
    row = measurements_rows[hour - 1]
IndexError: list index out of range
```

**Comment by riklmr** [comment]
Confirmed: the hauteur page inserts an extra table at index 3 holding information about the reference level.
This shifts the measurements table down one position, compared to debit or precipitation pages.
Possible workarounds:
1) use the table by index [-2] counting backwards from the end of array.
2) iterate over all tables and select the on that happens to have th tags in the first row (all other pages have td tags in the first row).

I prefer 1) because it is more obvious code to read.

**Comment by riklmr** [comment]
merged into develop and closed
