### ISSUE TITLE
Replace multi-level indexed df with simpler, elegant solution that we can understand

### ISSUE THREAD

**Issue by riklmr** [riklmr/chaudfontaine#5]
Tracking data coverage using a Pandas DataFrame with a four-level index proved too complex for such a simple task. It kept failing in different stages of the scrape. I now dedicate this Issue #5 to that problem.

Task: re-develop the tracking mechanism using something else than pd.

[edited: read old description below]

**Comment by riklmr** [comment]
Although css class changes with this special case, we just solve this by searching for any asterisk and removing them, silently.

**Comment by riklmr** [comment]
resolved

**Comment by riklmr** [comment]
Something went wrong with merging the resolution branch into develop. Probably did not push before merge.

**Comment by riklmr** [comment]
One bugfix leads to new bugs. I must re-examine my Pandas knowledge and repair my code.

**Comment by riklmr** [comment]
Re-defining this whole issue. Read re-edit above.

Old description was: 
### Commented values contain asterisk, cannot be parsed as float()
Example table with commented (annotated) values:
5572 debit 2017 1 [voies-hydrauliques.wallonie.be](http://voies-hydrauliques.wallonie.be/opencms/opencms/fr/hydro/Archive/annuaires/stathorairetab.do?code=55721002&annee=2017&mois=1&xt=prt)

chaudfontaine get_measurements_wallonie.py throws: 
```
Traceback (most recent call last):
  File "get_measurements_wallonie.py", line 598, in <module>
    
  File "get_measurements_wallonie.py", line 549, in etl_station_alltime
    [start_date, end_date] = parsePeriod(soup)
  File "get_measurements_wallonie.py", line 506, in process_station_month
    else:
  File "get_measurements_wallonie.py", line 472, in etl_station_month
    time.sleep(SLEEPTIME) # courtesy to the webserver
  File "get_measurements_wallonie.py", line 307, in parseMeasurements
    # if day - 1 > X.shape[1] - 1:
ValueError: could not convert string to float: '*0.82'
```
### Easily fixed
by checking for the existence of non-numerical chars and removing them. Using re.

**Comment by riklmr** [comment]
# On the issue of tracking data coverage
The new plan is to use a dict like:
```python
{ 
    serialized_key: status_string,
    serialized_key: status_string,
    ...,
    serialized_key: status_string
 }
```
Where the serialized_key is simply a stringed together version of four variables:
`serialized_key = "{}-{}-{}-{}".format(station_type, station_code, year, month)`
This looks like:
`'precipitation-5649-2019-6'`

While we are changing this, I also want the order of these four vars to be the same across the code: (station_type, station_code, year, month).

For persistence of the tracking dict, we use pickle.

**Comment by riklmr** [comment]
I already invested quite some time in scraping many pages. About 2.5 GB in Postgres. This coverage was recorded in csv. A little helper script will convert this to the newly proposed format of dicts 'n' pickles.

**Comment by riklmr** [comment]
Testing develop branch: works OK now. Issue closed.
